--SCRIPT JUST FOR H2 DATABASE: Local Spring Profile
--BED_TYPES
INSERT INTO BED_TYPES (NAME, SIZE) VALUES ('KING',2),('QUEEN',2),('SMALL SINGLE',1);


--ROOM_TYPES
INSERT INTO ROOM_TYPES (NAME, DESCRIPTION) VALUES ('Suite', 'Suite Room from H2');
INSERT INTO ROOM_TYPES (NAME, DESCRIPTION) VALUES ('Penthouse', 'Penthouse Room from H2');


--ROOMS
INSERT INTO ROOMS (DESCRIPTION, ROOM_NUMBER, FLOOR_NUMBER, ROOM_TYPE_ID, BED_TYPE_ID, PRICE) VALUES ('ROOM 1 FROM H2', 1, 1, 1, 2, 10.52);
INSERT INTO ROOMS (DESCRIPTION, ROOM_NUMBER, FLOOR_NUMBER, ROOM_TYPE_ID, BED_TYPE_ID, PRICE) VALUES ('ROOM 2 FROM H2', 2, 1, 1, 2, 15.53);
INSERT INTO ROOMS (DESCRIPTION, ROOM_NUMBER, FLOOR_NUMBER, ROOM_TYPE_ID, BED_TYPE_ID, PRICE) VALUES ('ROOM 3 FROM H2', 3, 2, 2, 1, 12.54);
INSERT INTO ROOMS (DESCRIPTION, ROOM_NUMBER, FLOOR_NUMBER, ROOM_TYPE_ID, BED_TYPE_ID, PRICE) VALUES ('ROOM 4 FROM H2', 3, 2, 2, 1, 11.55);

--CUSTOMERS
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, BIRTH_DATE, EMAIL, PHONE_NUMBER) VALUES ('Winnie', 'Dominguez', PARSEDATETIME('02-02-1990', 'dd-mm-yyyy'), 'winnie.dominguez@hotelapi.com', '8888-8888');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, BIRTH_DATE, EMAIL, PHONE_NUMBER) VALUES ('Luis', 'Lu', PARSEDATETIME('01-01-1990', 'dd-mm-yyyy'), 'luis.lu@hotelapi.com', '9999-9999');
INSERT INTO CUSTOMERS (FIRST_NAME, LAST_NAME, BIRTH_DATE, EMAIL, PHONE_NUMBER) VALUES ('Arlene', 'Tay', PARSEDATETIME('01-01-1990', 'dd-mm-yyyy'), 'arlene.tay@hotelapi.com', '1010-1010');

--RESERVATIONS
INSERT INTO RESERVATIONS (CUSTOMER_BILLED_ID, ROOM_ID, START_DATE, END_DATE, BILLING_DATE, AMOUNT) VALUES ('1', '1', PARSEDATETIME('09-08-2021', 'dd-mm-yyyy'), PARSEDATETIME('11-08-2021', 'dd-mm-yyyy'), PARSEDATETIME('05-08-2021', 'dd-mm-yyyy'), '21.04');
INSERT INTO RESERVATIONS (CUSTOMER_BILLED_ID, ROOM_ID, START_DATE, END_DATE, BILLING_DATE, AMOUNT) VALUES ('2', '1', PARSEDATETIME('12-08-2021', 'dd-mm-yyyy'), PARSEDATETIME('13-08-2021', 'dd-mm-yyyy'), PARSEDATETIME('05-08-2021', 'dd-mm-yyyy'), '21.04');

