--SCRIPT JUST FOR H2 DATABASE: Local Spring Profile

DROP TABLE IF EXISTS CUSTOMERS;
CREATE TABLE CUSTOMERS (
  CUSTOMER_ID int(11) NOT NULL AUTO_INCREMENT,
  FIRST_NAME varchar(45) NOT NULL,
  LAST_NAME varchar(45) NOT NULL,
  BIRTH_DATE date DEFAULT NULL,
  EMAIL varchar(45) DEFAULT NULL,
  PHONE_NUMBER varchar(45) DEFAULT NULL,
  PRIMARY KEY (CUSTOMER_ID)
);

DROP TABLE IF EXISTS BED_TYPES;
CREATE TABLE BED_TYPES (
  BED_TYPE_ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  SIZE int(11) NOT NULL,
  PRIMARY KEY (BED_TYPE_ID)
);

DROP TABLE IF EXISTS ROOM_TYPES;
CREATE TABLE ROOM_TYPES (
  ROOM_TYPE_ID int(11) NOT NULL AUTO_INCREMENT,
  NAME varchar(45) NOT NULL,
  DESCRIPTION varchar(45) NOT NULL,
  PRIMARY KEY (ROOM_TYPE_ID)
);

DROP TABLE IF EXISTS ROOMS;
CREATE TABLE ROOMS (
  ROOM_ID int(11) NOT NULL AUTO_INCREMENT,
  DESCRIPTION varchar(45) DEFAULT NULL,
  ROOM_NUMBER int(11) NOT NULL,
  FLOOR_NUMBER int(11) NOT NULL,
  ROOM_TYPE_ID int(11) NOT NULL,
  BED_TYPE_ID int(11) NOT NULL,
  PRICE double NOT NULL,
  PRIMARY KEY (ROOM_ID),
  KEY ROOMTYPEFK_IDX (ROOM_TYPE_ID),
  KEY BED_TYPE_ID_idx (BED_TYPE_ID),
  CONSTRAINT BED_TYPE_ID FOREIGN KEY (BED_TYPE_ID) REFERENCES BED_TYPES (BED_TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT ROOMTYPEFK FOREIGN KEY (ROOM_TYPE_ID) REFERENCES ROOM_TYPES (ROOM_TYPE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

CREATE TABLE RESERVATIONS (
  RESERVATION_ID int(11) NOT NULL AUTO_INCREMENT,
  CUSTOMER_BILLED_ID int(11) NOT NULL,
  ROOM_ID int(11) NOT NULL,
  START_DATE date NOT NULL,
  END_DATE date NOT NULL,
  BILLING_DATE datetime NOT NULL,
  AMOUNT double NOT NULL,
  PRIMARY KEY (RESERVATION_ID),
  KEY CUSTOMER_BILLED_ID_idx (CUSTOMER_BILLED_ID),
  KEY ROOM_ID_idx (ROOM_ID),
  CONSTRAINT CUSTOMER_BILLED_ID FOREIGN KEY (CUSTOMER_BILLED_ID) REFERENCES CUSTOMERS (CUSTOMER_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT ROOM_ID FOREIGN KEY (ROOM_ID) REFERENCES ROOMS (ROOM_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);



